name: windows

on: [push, pull_request]

jobs:
  windows-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        shared: [OFF, ON]
    name: "Windows MSVC ${{ matrix.shared == 'ON' && 'shared' || 'static' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Compile
        run: |
          cmake -B build -DORYX_CHRON_BUILD_TESTS=ON -DORYX_CHRON_BUILD_SHARED_LIBS=${{ matrix.shared }} -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run tests
        run: .\build\Debug\chron-cpp_tests
